name: Build DLLs

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.3

      - name: Restore NuGet packages
        run: nuget restore MMM.sln

      - name: Build solution
        run: msbuild MMM.sln /p:Configuration=Release /p:Platform="x86"

      - name: Upload DLLs
        uses: actions/upload-artifact@v4
        with:
          name: MMM-DLLs
          path: |
            **/bin/Release/*.dll
