name: .NET Core Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            2.1.x
            2.2.x

      - name: Restore NuGet packages for all projects
        run: |
          Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
            Write-Host "Restoring: $($_.FullName)"
            dotnet restore $_.FullName
          }

      - name: Build all .csproj files
        run: |
          Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
            Write-Host "Building: $($_.FullName)"
            dotnet build $_.FullName --configuration Release --no-restore
          }
