name: Build DLLs Without SLN

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Build all .csproj files
        run: |
          Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
            Write-Host "Building $($_.FullName)"
            msbuild $_.FullName /p:Configuration=Release /p:Platform="x86"
          }

      - name: Upload DLLs
        uses: actions/upload-artifact@v4
        with:
          name: MMM-DLLs
          path: |
            **/bin/Release/*.dll
